name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Format check
      run: sbt scalafmtCheck
    - name: Run tests
      run: sbt clean coverage test coverageReport
    # Runs a single command using the runners shell
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        # User defined upload name. Visible in Codecov UI
        name: kissconfig # optional
